config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/cart", to: "carts#show"
  get "/checkout", to: "carts#destroy"
  get "/history", to: "orders#index"
  get "sessions/new"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/upload", to: "products#new"
  post "/upload", to: "products#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/product_rating/:id", to: "products#rating", as: "rating"
  get "/suggestions", to: "suggestions#new"
  post "/suggestions", to: "suggestions#create"
  get "/recently", to: "recent_views#recently"
  get "/cart", to: "carts#show"
  get "/checkout", to: "carts#destroy"
  get "/history", to: "orders#index"

  resources :users
  resources :products
  resources :categories
  resources :orders
  resources :detail_orders, only: [:create, :update, :destroy]

  namespace :admin do
    root "static_pages#home"
    resources :users
    get "/import", to: "products#show"
    resources :products do
      collection {post :import}
    end
    resources :categories
    resources :suggestions
    resources :orders, only: %i(index update destroy)
    resources :detail_orders, only: :show
  end
end

app/views/admin/_block_bot.html.erb
</div>
</div>

app/views/admin/_block_top.html.erb
<div class="row fix admin-row">

app/views/admin/_nav_left.html.erb
<div class="col-sm-2 fix admin-nav-left">
<div class="navbar-default sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse my-sidebar">
  <ul class="nav in" id="side-menu">
    <li class="sidebar-search">
      <div class="input-group custom-search-form">
        <input type="text" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">
              <i class="fa fa-search"></i>
            </button>
          </span>
        </div>
        <!-- /input-group -->
      </li>
      <li>
        <%= link_to admin_home_path do %>
          <i class="fa fa-university" aria-hidden="true"></i> Admin
        <% end %>
      </li>

      <li>
        <%= link_to admin_users_path do %>
          <i class="fa fa-users"></i> User Management
        <% end %>
      </li>
      
      <li>
        <%= link_to admin_products_path do %>
          <i class="fa fa-tags" aria-hidden="true"></i> Product Management
        <% end %>
      </li>

      <li>
        <%= link_to admin_categories_path do %>
          <i class="fa fa-industry" aria-hidden="true"></i> Category Management
        <% end %>
      </li>

      <li>
        <a href="index.html" class="active">
          <i class="fa fa-paper-plane" aria-hidden="true"></i> Suggetion Management
        </a>
      </li>

    </ul>
  </div>
  <!-- /.sidebar-collapse -->
</div>
</div>