config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/cart", to: "carts#show"
  get "/checkout", to: "carts#destroy"
  get "/history", to: "orders#index"
  get "sessions/new"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/upload", to: "products#new"
  post "/upload", to: "products#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/product_rating/:id", to: "products#rating", as: "rating"
  get "/suggestions", to: "suggestions#new"
  post "/suggestions", to: "suggestions#create"
  get "/recently", to: "recent_views#recently"
  get "/cart", to: "carts#show"
  get "/checkout", to: "carts#destroy"
  get "/history", to: "orders#index"

  resources :users
  resources :products
  resources :categories
  resources :orders
  resources :detail_orders, only: [:create, :update, :destroy]

  namespace :admin do
    root "static_pages#home"
    resources :users
    get "/import", to: "products#show"
    resources :products do
      collection {post :import}
    end
    resources :categories
    resources :suggestions
    resources :orders, only: %i(index update destroy)
    resources :detail_orders, only: :show
  end
end

app/models/product.rb
class Product < ApplicationRecord
  VALID_MONEY_REGEX = /d*(\.d{1,2})?/

  has_many :ratings, dependent: :destroy
  has_many :users, through: :ratings
  has_many :detail_orders, dependent: :destroy
  belongs_to :category
  mount_uploader :picture, PictureUploader

  validates :name, presence: true, uniqueness: true,
    length: {maximum: Settings.product.name._max}
  validates :description, presence: true,
    length: {maximum: Settings.product.description._max}
  validates :category, presence: true
  validates :price, presence: true, format: {with: VALID_MONEY_REGEX}
  validates :rate, presence: true

  scope :hot_trend, -> do
    joins(:detail_orders)
    .group("detail_orders.product_id")
    .order("count(detail_orders.product_id) DESC")
    .limit(12)
  end
  scope :sort_alphabet_az, ->{order "name"}
  scope :sort_alphabet_za, ->{order "name desc"}
  scope :sort_price, ->{order "price desc"}
  scope :sort_rating, -> do
    left_joins(:ratings)
    .group("products.id")
    .order("(sum(ratings.rating)/count(products.id)) desc")
  end
  scope :sort_category, -> category_id {where category_id: category_id}
  scope :sort_category_children, -> categories_id do
    where("category_id IN (?)", categories_id)
  end
  scope :sort_product_updated, ->{order("created_at desc").limit(12)}
  scope :recently_products, -> list {where "id in (?)", list}
  scope :select_col, ->{attribute_names}

  def self.import_file file
    spreadsheet = Roo::Spreadsheet.open file
    header = spreadsheet.row 1
    orders = []
    (2..spreadsheet.last_row).each do |i|
      row = [header, spreadsheet.row(i)].transpose.to_h
      order = new row
      orders << order
    end
    import! orders
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin_layout"
  before_action :load_product, only: %i(edit update destroy)
  before_action :load_categories_select, only: %i(edit new create)

  def index
    @products = Product.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @category = Category.find_by(id: @product.category_id)
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t ".success"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t ".destroy-success"
    else
      flash[:success] = t ".destroy-fail"
    end

    redirect_to admin_products_path
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t ".created"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def show
    @products = Product.all
  end

  def import
    Product.import_file params[:file]
    redirect_to import_admin_products_path, notice: "Data imported"
  end

  private

  def product_params
    params.require(:product)
      .permit :name, :description, :category_id, :price, :picture
  end

  def load_product
    @product = Product.find_by(id: params[:id])
    return if @product.present?
    flash[:info] = t ".info"
    redirect_to root_path
  end

  def load_categories_select
    @categories = categories_option
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, :init_resentlies, only: %i(edit show update)
  before_action :load_categories_sort, except: :show
  before_action :category_name_to_id, only: %i(create update)

  def index
    @category_id = params[:category]
    @type_sort = params[:type_sort]
    if @category_id.blank? && @type_sort.blank?
      @products = Product.sort_product_updated.paginate(page: params[:page],
       per_page: Settings.paginate_for.sort_page)
    else
      @products = sort_style @category_id, @type_sort
    end

    render "products/index"
  end

  def show
    @detail_order = current_order.detail_orders.build
    @product_ratings = Rating.product_rating(@product.id)
    @product_on = star_on @product_ratings

    if logged_in?
      @user_rating = Rating.user_rating(@product.id, current_user.id)
      @user_on = user_star_on @user_rating[0]
    end

    add_resently @product.id
  end

  def rating
    load_product
    update = @product.ratings.find_by(user_id: current_user.id)

    if update.blank?
      Rating.create!(user_id: current_user.id,
       product_id: @product.id, rating: params[:point])
    else
      update.update_attributes(rating: params[:point])
    end

    show
  end

  def load_product
    @product = Product.find_by(id: params[:id])
    return if @product.present?
    flash[:info] = t ".info"
    redirect_to root_path
  end

  def validation_login
    flash[:warning] = t "Please login !!!"
    redirect_to root_path
  end

  def validation_login
    flash[:warning] = t ".plslogin"
    redirect_to root_path
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def load_product_columns
    exclude_columns = ["category_id", "picture", "image", "rate", "image", "created_at", "password_digest", "remember_digest", "updated_at"]
    columns = Product.select_col - exclude_columns
    columns
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def children_categories parent_id
    Category.children_category(parent_id)
  end

  def image_for product
    image_tag product.picture.url
  end

  # def nested_categories category
  #   category.map do |parent|
  #     # if parent.children.nil?
  #     #   content_tag(:div, parent.name)
  #     # else
  #     parent.name + content_tag(:div, nested_categories(parent.children))+ "---"
  #     # content_tag(:div, parent.name) + content_tag(:div, nested_categories(parent.children))
  #   end
  # end
end

app/views/admin/products/edit.html.erb
<div class="row fix height-default-js">
  <div class="col-sm-2"></div>
  <div class="col-sm-8 login-view">
    <h1>
      <%= t(".update") %>
    </h1>
    <%= form_for @product, url: admin_product_path do |f| %>
      <%= render "shared/product_error_messages" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.label :category %>
      <!-- categories select -->
      <% products_option = "" %>
      <% @categories.each do |cate| %>
        <% if @category.present? && @category.name == cate %>
          <% products_option += "<option value='"+cate.id.to_s+"' selected>"+cate.name+"</option>" %>
        <% else %>
          <% products_option += "<option value='"+cate.id.to_s+"'>"+cate.name+"</option>" %>
        <% end %>
      <% end %>
      <%= f.select :category_id, products_option.html_safe, {},
       { class: "form-control sort-cate"  }
      %>
      <!-- /categories select -->

      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
      
      <div class="form-group picture">
        <label>File input</label>
        <%= f.file_field :picture %>
      </div>

      <%= f.submit "SAVE", class: "btn btn-primary btn-block bt-edit" %>
    <% end %>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/admin/products/index.html.erb
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">MANAGER PRODUCT</h1>
  </div>
</div>
<!-- /title -->
<!-------------- Table ----------------->
<div class="row">
<div class="col-sm-12">
<div class="panel panel-default mytable">
  <div class="panel-heading">
    PRODUCTS
  </div>
<!-- /.panel-heading -->
<div class="panel-body">
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <tr>
      <% columns = load_product_columns %>
      <% columns.each do |col| %>
        <th><%= col.capitalize %></th>
      <% end %>
      <th width="80px">EDIT</th>
      <th width="100px">DELETE</th>
    </tr>
    <tr>
    <!-- table user -->
    <% @products.each do |p| %>
    <tr>
      <% for i in 0...columns.count do %>
      <td><%= p[columns[i]] %></td>
      <% end %>
      <td class="table-update">
        <%= link_to edit_admin_product_path(p) do %>
          <i class="fa fa-pencil-square-o" aria-hidden="true"></i> EDIT
        <% end %>
      </td>
      <td class="table-delete">
        <%= link_to admin_product_path(p), method: :delete, data: {confirm: "You sure?"} do %>
           <i class="fa fa-trash-o" aria-hidden="true"></i> DELETE
        <% end %>
      </td>
    </tr>
    <% end %>
    <!-- /table user -->
  </table>
<div>
  <%= link_to t(".add_new"), new_admin_product_path %>
</div>
</div>
  <%= will_paginate @products %>
</div>
</div>
</div>
</div>

app/views/admin/products/new.html.erb
<div class="row fix height-default-js">
  <div class="col-sm-2"></div>
  <div class="col-sm-8 login-view">
    <h1>
      <%= t(".new") %>
    </h1>
    <%= form_for @product, url: admin_products_path do |f| %>
      <%= render "shared/product_error_messages" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.label :category %>
      <!-- categories select -->
      <% products_option = "" %>
      <% @categories.each do |cate| %>
        <% if @category.present? && @category.name == cate %>
          <% products_option += "<option value='"+cate.id.to_s+"' selected>"+cate.name+"</option>" %>
        <% else %>
          <% products_option += "<option value='"+cate.id.to_s+"'>"+cate.name+"</option>" %>
        <% end %>
      <% end %>
      <%= f.select :category_id, products_option.html_safe, {},
       { class: "form-control sort-cate"  }
      %>
      <!-- /categories select -->

      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
      
      <div class="form-group picture">
        <label>File input</label>
        <%= f.file_field :picture %>
      </div>

      <%= f.submit "CREATE", class: "btn btn-primary btn-block bt-edit" %>
    <% end %>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/admin/products/show.html.erb
<%= flash[:notice]%>
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}
 td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}
 tr:nth-child(even) {
    background-color: #dddddd;
}
</style>
<table>
  <thead>
  <tr>
    <th>Index</th>
    <th>Name</th>
    <th>Description</th>
    <th>Category</th>
    <th>Price</th>
  </tr>
  </thead>
  <tbody>
  <% @products.each_with_index do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= product.category.name %></td>
      <td><%= product.price %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div>
  <h4>Import data</h4>
  <%= form_tag import_admin_products_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import", class: "btn btn-primary" %>
  <% end %>
</div>