config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/cart", to: "carts#show"
  get "/checkout", to: "carts#destroy"
  get "/history", to: "orders#index"
  get "sessions/new"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/upload", to: "products#new"
  post "/upload", to: "products#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/product_rating/:id", to: "products#rating", as: "rating"
  get "/suggestions", to: "suggestions#new"
  post "/suggestions", to: "suggestions#create"
  get "/recently", to: "recent_views#recently"
  get "/cart", to: "carts#show"
  get "/checkout", to: "carts#destroy"
  get "/history", to: "orders#index"

  resources :users
  resources :products
  resources :categories
  resources :orders
  resources :detail_orders, only: [:create, :update, :destroy]

  namespace :admin do
    root "static_pages#home"
    resources :users
    get "/import", to: "products#show"
    resources :products do
      collection {post :import}
    end
    resources :categories
    resources :suggestions
    resources :orders, only: %i(index update destroy)
    resources :detail_orders, only: :show
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ratings
  has_many :products, through: :ratings
  has_many :suggestion
  has_many :orders
  attr_accessor :remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  VALID_PHONE_REGEX = /(09|03|05|07|08)+([0-9]{8})\b/
  before_save ->{email.downcase!}
  validates :name, presence: true, length: {maximum: Settings.user.name._max}
  validates :email, presence: true, length: {maximum: Settings.user.email._max},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :address, presence: true
  validates :phone, presence: true, format: {with: VALID_PHONE_REGEX}
  validates :password, length: {minimum: Settings.user.password._min},
   allow_nil: true
  enum role: {customer: 0, admin: 1}
  scope :select_col, ->{attribute_names}
  has_secure_password

  class <<self
    def digest string
      cost =
        if ActiveModel::SecurePassword.min_cost
          BCrypt::Engine::MIN_COST
        else
          BCrypt::Engine.cost
        end
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated? remember_token
    return false if remember_digest.blank?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin_layout"
  before_action :load_user, only: %i(edit update destroy)

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def edit; end

  def update
    if @user.update_attributes user_params
      flash[:success] = t ".updated"
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t ".delete"
    else
       flash[:success] = t ".delete_fail"
    end

    redirect_to admin_users_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t ".created"
      redirect_to admin_users_path
    else
      flash[:danger] = t ".danger"
      render :new
    end
  end

  private

  def user_params
    params.require(:user)
      .permit :name, :email, :phone, :address, :role,
       :password, :password_confirmation
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user.present?
    flash[:info] = t ".no_found"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: %i(index create user_params logged_in new)
  before_action :correct_user, only: %i(edit update show)
  before_action :logged_in_user, only: %i(edit update index destroy)
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      remember @user
      flash[:success] = t ".welcome", u: @user.name
      redirect_to root_path
    else
      flash[:danger] = t ".danger"
      render :new
    end
  end

  def edit; end

  def update
    if @user.update_attributes user_params
      flash[:success] = t ".updated"
      if current_user.customer?
        redirect_to @user
      else
        redirect_to admin_users_path
      end
    else
      if current_user.customer?
        render :edit
      else
        render "admin/users/edit"
      end
    end
  end

  def destroy
    @user.destroy
    flash[:success] = t".delete"
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user)
      .permit :name, :email, :phone, :address, :password, :password_confirmation
  end

  def correct_user
    if !(current_user? @user) && current_user.customer?
      redirect_to root_path
      flash[:danger] = t ".permit"
    end
  end

  def logged_in_user
    return if logged_in?
    store_location
    flash[:info] = t ".info"
    redirect_to login_path
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user.present?
    flash[:info] = t ".no_found"
    redirect_to root_path
  end

  def admin_user
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def load_user_columns
    exclude_columns = ["password", "password_digest", "remember_digest", "updated_at"]
    columns = User.select_col - exclude_columns
    columns
  end
  def load_role
    User.roles
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: Settings.gravatar.size}
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/admin/users/edit.html.erb
<div class="row fix height-default-js">
  <div class="col-sm-2"></div>
  <div class="col-sm-8 login-view">
    <h1>
      <%= t(".update") %>
    </h1>
    <%= form_for @user, url: admin_user_path do |f| %>
      <%= render "shared/error_messages" %>

      <%= f.label :role %>
      <!-- role select -->
      <% products_option = "" %>
      <% load_role.each do |r| %>
        <% if @user.role == r[0] %>
          <% products_option += "<option selected>"+r[0]+"</option>" %>
        <% else %>
          <% products_option += "<option>"+r[0]+"</option>" %>
        <% end %>
      <% end %>
      <%= f.select :role, products_option.html_safe, {},
       { class: "form-control sort-cate"  }
      %>
      <!-- /role select -->

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :phone %>
      <%= f.telephone_field :phone, class: "form-control" %>

      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <div class="gravatar_edit">
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails" target="_blank">
          <%= t(".change") %></a>
      </div>
      <%= f.submit t(".save"), class: "btn btn-primary btn-block bt-edit" %>
    <% end %>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/admin/users/home.html.erb
<%= render partial: "admin/block_top" %>
<%= render partial: "admin/nav_left" %>
<div class="col-sm-10 admin-right">
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">ADMIN PAGE</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-comments fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">26</div>
            <div>New Comments!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right">
            <i class="fa fa-arrow-circle-right"></i>
          </span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-green">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-tasks fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">12</div>
            <div>New Tasks!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right">
            <i class="fa fa-arrow-circle-right"></i>
          </span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-yellow">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-shopping-cart fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">124</div>
            <div>New Orders!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right">
            <i class="fa fa-arrow-circle-right"></i>
          </span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-red">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-support fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">13</div>
            <div>Support Tickets!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right">
            <i class="fa fa-arrow-circle-right"></i>
          </span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
</div>
    <%= content_tag :div, "", height: 50, id: "orders_chart",
      data: {orders: Order.total_grouped_by_month} %>
    <%= content_tag :h3,
      t(".graph",u: Date.today.strftime("%Y").to_i), align: "center" %>
</div>
<%= render partial: "admin/block_bot" %>
<script type="text/javascript" src = "/assets/admin/chart.js"></script>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header"><%= t ".mana_user" %></h1>
  </div>
</div>
<!-- /title -->
<!-------------- Table ----------------->
<div class="row">
<div class="col-sm-12">
<div class="panel panel-default mytable">
  <div class="panel-heading">
    <%= t ".title_table" %>
  </div>
<!-- /.panel-heading -->
<div class="panel-body">
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <tr>
      <% columns = load_user_columns %>
      <% columns.each do |col| %>
        <th><%= col.capitalize %></th>
      <% end %>
      <th width="80px">EDIT</th>
      <th width="100px">DELETE</th>
    </tr>
    <tr>
    <!-- table user -->
    <% @users.each do |u| %>
    <tr>
      <% for i in 0...columns.count do %>
      <td><%= u[columns[i]] %></td>
      <% end %>
      <td class="table-update">
        <%= link_to edit_admin_user_path u do %>
          <i class="fa fa-pencil-square-o" aria-hidden="true"></i> EDIT
        <% end %>
      </td>
      <td class="table-delete">
        <%= link_to admin_user_path(u), method: :delete, data: {confirm: "You sure?"} do %>
           <i class="fa fa-trash-o" aria-hidden="true"></i> DELETE
        <% end %>
      </td>
    </tr>
    <% end %>
    <!-- /table user -->
  </table>
<div>
  <%= link_to t(".add_new"), new_admin_user_path %>
</div>
</div>
  <%= will_paginate @users %>
</div>
</div>
</div>
</div>

app/views/admin/users/index.js.erb
$(document).on("turbolinks:load", function(){hs("admin-menu-1");});

app/views/admin/users/new.html.erb
<div class="row fix height-default-js">
  <div class="col-sm-2"></div>
  <div class="col-sm-8 login-view">
    <h1>
      <%= t(".new_title") %>
    </h1>
    <%= form_for @user, url: admin_users_path do |f| %>
      <%= render "shared/error_messages" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :phone %>
      <%= f.telephone_field :phone, class: "form-control" %>

      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <br>
      <%= f.submit t(".save"), class: "btn btn-primary btn-block bt-edit" %>
    <% end %>
  </div>
  <div class="col-sm-2"></div>
</div>