config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/cart", to: "carts#show"
  get "/checkout", to: "carts#destroy"
  get "/history", to: "orders#index"
  get "sessions/new"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/upload", to: "products#new"
  post "/upload", to: "products#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/product_rating/:id", to: "products#rating", as: "rating"
  get "/suggestions", to: "suggestions#new"
  post "/suggestions", to: "suggestions#create"
  get "/recently", to: "recent_views#recently"
  get "/cart", to: "carts#show"
  get "/checkout", to: "carts#destroy"
  get "/history", to: "orders#index"

  resources :users
  resources :products
  resources :categories
  resources :orders
  resources :detail_orders, only: [:create, :update, :destroy]

  namespace :admin do
    root "static_pages#home"
    resources :users
    get "/import", to: "products#show"
    resources :products do
      collection {post :import}
    end
    resources :categories
    resources :suggestions
    resources :orders, only: %i(index update destroy)
    resources :detail_orders, only: :show
  end
end

app/models/product.rb
class Product < ApplicationRecord
  VALID_MONEY_REGEX = /d*(\.d{1,2})?/

  has_many :ratings, dependent: :destroy
  has_many :users, through: :ratings
  has_many :detail_orders, dependent: :destroy
  belongs_to :category
  mount_uploader :picture, PictureUploader

  validates :name, presence: true, uniqueness: true,
    length: {maximum: Settings.product.name._max}
  validates :description, presence: true,
    length: {maximum: Settings.product.description._max}
  validates :category, presence: true
  validates :price, presence: true, format: {with: VALID_MONEY_REGEX}
  validates :rate, presence: true

  scope :hot_trend, -> do
    joins(:detail_orders)
    .group("detail_orders.product_id")
    .order("count(detail_orders.product_id) DESC")
    .limit(12)
  end
  scope :sort_alphabet_az, ->{order "name"}
  scope :sort_alphabet_za, ->{order "name desc"}
  scope :sort_price, ->{order "price desc"}
  scope :sort_rating, -> do
    left_joins(:ratings)
    .group("products.id")
    .order("(sum(ratings.rating)/count(products.id)) desc")
  end
  scope :sort_category, -> category_id {where category_id: category_id}
  scope :sort_category_children, -> categories_id do
    where("category_id IN (?)", categories_id)
  end
  scope :sort_product_updated, ->{order("created_at desc").limit(12)}
  scope :recently_products, -> list {where "id in (?)", list}
  scope :select_col, ->{attribute_names}

  def self.import_file file
    spreadsheet = Roo::Spreadsheet.open file
    header = spreadsheet.row 1
    orders = []
    (2..spreadsheet.last_row).each do |i|
      row = [header, spreadsheet.row(i)].transpose.to_h
      order = new row
      orders << order
    end
    import! orders
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin_layout"
  before_action :load_product, only: %i(edit update destroy)
  before_action :load_categories_select, only: %i(edit new create)

  def index
    @products = Product.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @category = Category.find_by(id: @product.category_id)
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t ".success"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t ".destroy-success"
    else
      flash[:success] = t ".destroy-fail"
    end

    redirect_to admin_products_path
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t ".created"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def show
    @products = Product.all
  end

  def import
    Product.import_file params[:file]
    redirect_to import_admin_products_path, notice: "Data imported"
  end

  private

  def product_params
    params.require(:product)
      .permit :name, :description, :category_id, :price, :picture
  end

  def load_product
    @product = Product.find_by(id: params[:id])
    return if @product.present?
    flash[:info] = t ".info"
    redirect_to root_path
  end

  def load_categories_select
    @categories = categories_option
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, :init_resentlies, only: %i(edit show update)
  before_action :load_categories_sort, except: :show
  before_action :category_name_to_id, only: %i(create update)

  def index
    @category_id = params[:category]
    @type_sort = params[:type_sort]
    if @category_id.blank? && @type_sort.blank?
      @products = Product.sort_product_updated.paginate(page: params[:page],
       per_page: Settings.paginate_for.sort_page)
    else
      @products = sort_style @category_id, @type_sort
    end

    render "products/index"
  end

  def show
    @detail_order = current_order.detail_orders.build
    @product_ratings = Rating.product_rating(@product.id)
    @product_on = star_on @product_ratings

    if logged_in?
      @user_rating = Rating.user_rating(@product.id, current_user.id)
      @user_on = user_star_on @user_rating[0]
    end

    add_resently @product.id
  end

  def rating
    load_product
    update = @product.ratings.find_by(user_id: current_user.id)

    if update.blank?
      Rating.create!(user_id: current_user.id,
       product_id: @product.id, rating: params[:point])
    else
      update.update_attributes(rating: params[:point])
    end

    show
  end

  def load_product
    @product = Product.find_by(id: params[:id])
    return if @product.present?
    flash[:info] = t ".info"
    redirect_to root_path
  end

  def validation_login
    flash[:warning] = t "Please login !!!"
    redirect_to root_path
  end

  def validation_login
    flash[:warning] = t ".plslogin"
    redirect_to root_path
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def load_product_columns
    exclude_columns = ["category_id", "picture", "image", "rate", "image", "created_at", "password_digest", "remember_digest", "updated_at"]
    columns = Product.select_col - exclude_columns
    columns
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def children_categories parent_id
    Category.children_category(parent_id)
  end

  def image_for product
    image_tag product.picture.url
  end

  # def nested_categories category
  #   category.map do |parent|
  #     # if parent.children.nil?
  #     #   content_tag(:div, parent.name)
  #     # else
  #     parent.name + content_tag(:div, nested_categories(parent.children))+ "---"
  #     # content_tag(:div, parent.name) + content_tag(:div, nested_categories(parent.children))
  #   end
  # end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <%= render "shared/product_error_messages" %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.label :category %>
  <!-- categories select -->
  <% products_option = "<option>-- Categories --</option>" %>
  <% @categories_for_sort.each do |cate| %>
    <% if @category_sort.present? && @category_sort == cate %>
      <% products_option += "<option selected>"+cate+"</option>" %>
    <% else %>
      <% products_option += "<option>"+cate+"</option>" %>
    <% end %>
  <% end %>
  <%= f.select "category", products_option.html_safe, {},
       { class: "form-control sort-cate" }
  %>
  <!-- /categories select -->

  <%= f.label :price %>
  <%= f.text_field :price, class: "form-control" %>
  
  <div class="form-group">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>

  <br>
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block bt-edit" %>
<% end %>

app/views/products/_product_rating.html.erb
<% for i in 1..5 %>
  <% if i <= product_on %>
    <%= image_tag("rating/star-on.png") %>
  <% else %>
    <%= image_tag("rating/star-off.png") %>
  <% end %>
<% end %>

app/views/products/_product_row.html.erb
<%= form_for @detail_order do |f| %>
<%= f.hidden_field :product_id, value: product.id %>
<div>
  <%= f.number_field :quantity, value: 1, class: "form-control show-quantity", min: 1 %>
  <%= f.submit t(".add"), class: "buy-now" %>
</div>
<% end %>

app/views/products/_select_sort.html.erb
<%= form_tag products_path, class: "sort-left", method: "get" do %>
  <!-- categories select -->
  <%# products_option = "<option>-- Categories --</option>" %>
  <%# @categories_for_sort.each do |cate| %>
    <%# if @category_sort.present? && @category_sort == cate.name %>
      <%# products_option += "<option selected>---"+cate.name+"</option>" %>
    <%# else %>
      <%# products_option += "<option>"+cate.name+"</option>" %>
    <%# end %>
  <%# end %>

  <!-- Tue -->
  <% products_option = "<option>-- Categories --</option>" %>
  <% @categories_for_sort.each do |cate| %>
    <% if @category_id.present? && @category_id == cate.id.to_s %>
      <% products_option += "<option value='"+cate.id.to_s+"' selected>"+cate.name+"</option>" %>
    <% else %>
      <% products_option += "<option value='"+cate.id.to_s+"' >"+cate.name+"</option>" %>
    <% end %>
  <% end %>
<!--     def nested_categories(categories)
    categories.map do |parent, children|
      parent.name + nested_categories(children)
    end
  end -->
 <!-- Tue -->


  <%= select_tag "category",products_option.html_safe,
    class: "form-control sort-cate" %>
  <!-- /categories select -->
  <!-- type select -->
  <% arr_type_option = ["A-Z",
    "Z-A",
    "Price",
    "Rating"] %>
  <% type_option = "<option>-- Sort by --</option>" %>
  <% arr_type_option.each do |type| %>
    <% if @type_sort.present? && @type_sort == type %>
      <% type_option += "<option selected>"+type+"</option>" %>
    <% else %>
      <% type_option += "<option>"+type+"</option>" %>
    <% end %>
  <% end %>
  <%= select_tag "type_sort", type_option.html_safe,
    class: "form-control sort-cate"
  %>
  <!-- /type select -->
  <%= submit_tag "Filter", class: "btn btn-default" %>
<% end %>

app/views/products/_user_rating.html.erb
<% for i in 1..5 %>
  <% if i<=user_on %>
    <!-- star on -->
    <%= link_to rating_path(point: i, old: request.original_url), remote: true, method: :post do %>
          <%= image_tag("rating/star-on.png",title: "#{i}", class: "user_rating") %>
    <% end %>
    <!-- /star on -->
  <% else %>
    <!-- star off -->
    <%= link_to rating_path(point: i, old: request.original_url), remote: true, method: :post do %>
          <%= image_tag("rating/star-off.png",title: "#{i}", class: "user_rating") %>
    <% end %>
    <!-- /star off -->
  <% end %>
<% end %>

app/views/products/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".save") %>
<div class="row fix height-default-js">
  <div class="col-sm-4"></div>
  <div class="col-sm-4 login-view">
    <h1>
      <%= t(".title") %>
    </h1>
    <%= form_for(@product) do |f| %>
      <%= render "shared/product_error_messages" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.label :category %>
      <!-- categories select -->
      <% products_option = "" %>
      <% @categories_for_sort.each do |cate| %>
        <% if @category.present? && @category.name == cate %>
          <% products_option += "<option selected>"+cate+"</option>" %>
        <% else %>
          <% products_option += "<option>"+cate+"</option>" %>
        <% end %>
      <% end %>
      <%= f.select "category", products_option.html_safe, {},
       { class: "form-control sort-cate" }
      %>
      <!-- /categories select -->

      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
        
      <div class="form-group">
        <%= f.label :picture %>
        <%= f.file_field :picture %>
      </div>
        
      <%= f.submit yield(:button_text), class: "btn btn-primary  btn-block bt-edit" %>
    <% end %>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/products/index.html.erb
<% provide :title, t(".title") %>
<!-- SORT -->
<div class="row pd-sort fix height-default-js">
<div class="col-sm-1"></div>
<div class="col-sm-10 fix">
  <div class="prod-title none-border">
    <%= link_to "javascript:void(0)" do %>
      <i class="fa fa-sort-amount-asc" aria-hidden="true"></i> <%= t ".title_sort" %>
    <% end %>

    <%= render "select_sort" %>
  </div>
  <div class="row product">
    <div class="col-sm-12">
      <% if @products.blank? %>
        <center>0 Result</center>
      <% else %>
        <% @products.each do |product| %>
        <div class="col-sm-2 pi fix">
          <%= link_to product do %>
            <%= image_tag(product.picture.url, class: "img") %>
            <div class="content">
              <div class="line"></div>
              <p class="citem"><%= number_to_currency(product.price)%></p>
              <h4 class="citem"><%= product.name %></h4>
            </div>
            <div class="topbg">&nbsp;</div>
          <% end %>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= will_paginate @products %>
</div>
<div class="col-sm-1"></div>
</div>
<!-- /SORT -->

app/views/products/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".sell") %>
<div class="row fix height-default-js">
  <div class="col-sm-4"></div>
  <div class="col-sm-4 login-view">
    <h1>
      <%= t(".title") %>
    </h1>
    <%= render "form" %>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/products/rating.js.erb
$("#product_rating").html("<%= j render partial: 'product_rating', locals: {product_on: @product_on} %> ")
$("#user_rating").html("<%= j render partial: 'user_rating', locals: {user_on: @user_on} %> ")
$("#thank_rating").html("<span style='color:green'>Thank you for your review :D</span>")
$(document).ready(function(){
  rating_run();
});

app/views/products/show.html.erb
<% provide :title, @product.name %>
<div class="row fix height-default-js">
<div class="col-sm-1"></div>
<div class="col-sm-10 fix">
  <!-- Product detail -->
  <div class="page_header">
    <%= t ".title" %>
  </div>
  <div class="page_down">
    <i class="fa fa-caret-down" aria-hidden="true" style="font-size: 24px;"></i>
  </div>

  <div class="row product-detail fix">
    <div class="col-sm-7 pd-left fix">
      <%= image_for @product %>
    </div>
    <div class="col-sm-5 pd-right">
      <h4><i class="fa fa-check" aria-hidden="true" Style="color:green"></i>
        <%= @product.name %>
      </h4>
      <div class="start" id="product_rating">
        <%= render partial: "product_rating", locals: {product_on: @product_on} %>
      </div>
      <div class="gia"><i class="fa fa-money" aria-hidden="true"></i>
        <%= number_to_currency(@product.price) %>
      </div>
      <span class="pd_click">
        <%= render "product_row", product: @product%>
        <%= link_to t(".seecart"), cart_path, class: "your-cart" %>
      </span>
    </div>
  </div>
  <!-- /Product detail -->
</div>

<!-- Mô tả SP -->
<div class="container con-hunder">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home"><%= t ".decrip" %></a></li>
    <% if logged_in? %>
      <li><a data-toggle="tab" href="#menu1"><%= t ".rating" %></a></li>
    <% end %>
  </ul>

  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
      <h3><%= t ".decrip" %></h3>
      <p><%= @product.description %></p>
    </div>
    <% if logged_in? %>
      <div id="menu1" class="tab-pane fade">
        <br>
          <p><i id="thank_rating">
          <% if @user_on.zero? %>
            <%= t ".not_rated" %>
          <% else %>
            <%= t ".ever_rated" %>
          <% end %>
          </i></p>
        <div class="start" id="user_rating">
        <%= render partial: "user_rating", locals: {user_on: @user_on} %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<!-- /Mô tả SP -->